name: Tech Portal Indonesia
title: Tech Portal Indonesia
description: Latest tech issues and tutorials
logo: assets/images/techs.png
favicon: assets/images/techico.png
baseurl: ''
google_analytics: ''
include:
  - _pages
permalink: '/:title/'
authors:
  techidn:
    name: Techidn
    display_name: Techidn
    email: krvsuite@gmail.com
    twitter: ''
    description: "Ikuti kami untuk mendapatkan info terbaru seputar aplikasi dan teknologi berbasis kecerdasan buatan di era industri digital."
    web: "https://techidn.github.io"
    gravatar: 0397aa39d5259d69961beaf1155fa085
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: 'disabled'
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: 'enabled'
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links:
    - datafiles
